version: '3.5'

services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
       -/usr/src/app/node_modules
    ports:
      - 8080:80
    depends_on:
      - server
    networks:
      front:

  server:
   
    environment:
      - APP_SETTINGS=production
      - FLASK_APP=wsgi.py
      - FLASK_ENV=production
    command: gunicorn -w 4 -b :8000 wsgi:app



 
